from django.urls import path
from .views import (
    InboundDeliveryListCreateAPIView,
    InboundDeliveryDetailsAPIView,
    OutboundDeliveryDetailsAPIView,
    OutboundDeliveryListCreateAPIView,
    InboundDeliveryRetrieveUpdateAPIView,
    UpdateInboundDelStatus,
    GetTotalOutboundPendingCount,
    GetTotalInboundPendingCount,
)

urlpatterns = [
    path(
        "customer",
        OutboundDeliveryListCreateAPIView.as_view(),
        name="customer-delivery-list-create",
    ),
    path(
        "customer/<int:pk>/details",
        OutboundDeliveryDetailsAPIView.as_view(),
        name="customer-delivery-details",
    ),
    path(
        "supplier",
        InboundDeliveryListCreateAPIView.as_view(),
        name="supplier-delivery-list-create",
    ),
    path(
        "supplier/<int:pk>/",
        InboundDeliveryRetrieveUpdateAPIView.as_view(),
        name="supplier-delivery-retrieve-update",
    ),
    path(
        "supplier/<int:pk>/details",
        InboundDeliveryDetailsAPIView.as_view(),
        name="supplier-delivery-details",
    ),
    path(
        "supplier/<int:pk>/update",
        UpdateInboundDelStatus.as_view(),
        name="update-inbound-status",
    ),
    path(
        "customer/total-orders",
        GetTotalOutboundPendingCount.as_view(),
        name="total-customer-pending",
    ),
    path(
        "supplier/total-orders",
        GetTotalInboundPendingCount.as_view(),
        name="total-supplier-pending",
    ),
]
