# Generated by Django 5.1.3 on 2024-11-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Supp_Company_Name", models.CharField(max_length=255)),
                ("Supp_Company_Num", models.CharField(max_length=15)),
                ("Supp_Contact_Pname", models.CharField(max_length=255)),
                ("Supp_Contact_Num", models.CharField(max_length=15)),
            ],
        ),
    ]
