# Generated by Django 5.1.3 on 2025-01-08 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderRequest",
            fields=[
                ("ORDER_ID", models.AutoField(primary_key=True, serialize=False)),
                ("ORDER_DATE_CREATED", models.DateTimeField(auto_now_add=True)),
                ("ORDER_DATE_UPDATED", models.DateTimeField(auto_now=True)),
                (
                    "ORDER_STATUS",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Shipped", "Shipped"),
                            ("Delivered", "Delivered"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("CLIENT_ID", models.IntegerField(null=True)),
                (
                    "ORDER_CREATEDBY_USER",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Request",
                "verbose_name_plural": "Order Requests",
                "db_table": "ORDER_REQUEST",
            },
        ),
        migrations.CreateModel(
            name="OrderRequestDetails",
            fields=[
                (
                    "ORDER_REQ_DETAILS_ID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("ORDER_REQ_PRODUCT_ID", models.IntegerField(blank=True, null=True)),
                ("ORDER_REQ_PRODUCT_NAME", models.CharField(max_length=50)),
                ("ORDER_REQ_QTY", models.PositiveIntegerField()),
                (
                    "ORDER_REQ_PRICE",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "ORDER_REQ_LINE_TOTAL",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "ORDER_REQ_SUB_TOTAL",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "ORDER_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_details",
                        to="Request.orderrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Request Detail",
                "verbose_name_plural": "Order Request Details",
                "db_table": "ORDER_REQUEST_DETAILS",
            },
        ),
    ]
